# Generated by Django 5.1.4 on 2024-12-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('from_currency', models.CharField(blank=True, max_length=3, verbose_name='From Currency')),
                ('to_currency', models.CharField(blank=True, max_length=3, verbose_name='To Currency')),
                ('converted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Converted')),
            ],
            options={
                'verbose_name': 'Currency Exchange',
                'verbose_name_plural': 'Currency Exchanges',
            },
        ),
    ]
