# Generated by Django 5.1.4 on 2024-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='from_currency',
            field=models.CharField(blank=True, verbose_name='From Currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='to_currency',
            field=models.CharField(blank=True, verbose_name='To Currency'),
        ),
    ]
