# Generated by Django 5.1.4 on 2024-12-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_alter_currencyexchange_from_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, verbose_name='Continent/Country')),
            ],
        ),
    ]
