# Generated by Django 5.1.4 on 2024-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0003_countrytimemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytimemodel',
            name='country_time',
            field=models.TextField(blank=True, verbose_name='CountryTime'),
        ),
    ]
