# Generated by Django 5.1.5 on 2025-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0004_countrytimemodel_country_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Untitled', max_length=50)),
                ('description', models.TextField(blank=True, default='No description')),
                ('genres', models.CharField(blank=True, default='No genres', max_length=255)),
                ('release_time', models.CharField(blank=True, default='No release time', max_length=50)),
                ('image', models.URLField(blank=True, default='No release time')),
                ('platforms', models.CharField(blank=True, default='No platforms', max_length=255)),
                ('developers', models.CharField(blank=True, default='No developers', max_length=255)),
            ],
        ),
    ]
